### ISSUE TITLE
CANDLE NIH Workshop Feb 21-22

### ISSUE THREAD

**Issue by georgezakinih** [NIHDataScienceSIG/nihdatasciencesig.github.io#14]
Do you have massive amounts of data? Have you heard about deep learning and machine learning and would like to learn to utilize these approaches in your research? Join us for the CANDLE workshop to explore one of many ways high-performance computing can be used to tackle cancer research challenges and advance precision oncology.

The CANDLE workshop is a collaboration between the NCI Center for Biomedical Informatics and Information Technology, Frederick National Laboratory for Cancer Research, and the Department of Energy’s (DOE) National Laboratories (Argonne, Lawrence Livermore, Los Alamos, and Oak Ridge). The CANDLE workshop will help you “wrangle the big data tsunami” using deep learning and machine learning applied to cancer and related diseases to increase your avenues to scientific insight.

In person registration is full, but you can use the webex:

Day 1 – Wednesday, February 21, 2018
WebEx URL: https://cbiit.webex.com/cbiit/j.php?MTID=m97e96d5cf93fdf6e3bac752d99ff0293
Phone: 650.479.3207
Meeting Number: 734 267 405
Password: RyFPVd@9
 
Day 2 – Thursday, February 22, 2018
WebEx URL: https://cbiit.webex.com/cbiit/j.php?MTID=mc694a1220f4876926aa18d264f870286
Phone: 650.479.3207
Meeting Number: 732 881 078
Password: tZKJ2uB@

**Comment by seandavi** [comment]
Added in df3c7ff929c95d6cc3. Thanks, @georgezakinih.
